export const guides = {
  tr: [
    {
      title: "Discord Sunucusu Nasıl Güvenli Bir Şekilde Klonlanır? (Adım Adım Rehber)",
      content: "Discord sunucunuzu kopyalamak, özellikle büyük toplulukları yeni bir yapıya taşırken veya kritik verileri yedeklerken oldukça hassas bir işlemdir. İlk adım olarak, kopyalamak istediğiniz (kaynak) sunucuda ve verileri aktaracağınız (hedef) sunucuda gerekli yetkilere sahip olduğunuzdan emin olmalısınız. OX Cloner, kullanıcı token'ınızı kullanarak bu iki sunucu arasında güvenli bir köprü kurar.\n\nİşlem sırasında 'Güvenli Mod' (Safe Mode) seçeneğini kullanmanız, Discord'un otomatik bot tespit sistemlerine yakalanmanızı önler. Bu modda işlemler daha yavaş ancak çok daha kararlı bir şekilde ilerler. Kanalların sıralaması, kategori izinleri ve özel emoji setleri, sistemimiz tarafından birebir analiz edilerek hedef sunucuda yeniden inşa edilir. Unutmayın, bu işlem sırasında hesabınızın 'Yönetici' yetkisine sahip olması, tüm gizli kanalların ve özel rollerin eksiksiz taşınması için şarttır."
    },
    {
      title: "Dijital Topluluklar İçin Sunucu Yedeklemenin Hayati Önemi",
      content: "Bir Discord sunucusu sadece bir sohbet alanı değil, binlerce saatlik emeğin, özel içeriklerin ve karmaşık bir organizasyon yapısının ürünüdür. Siber saldırılar, yetkisiz bot kullanımları veya yönetici hataları sonucunda bu yapının saniyeler içinde yok olması mümkündür. İşte bu noktada düzenli 'Sunucu Yedekleme' (Backup) devreye girer.\n\nOX Cloner ile sunucunuzun anlık bir 'şablonunu' (template) başka bir boş sunucuda saklamak, olası bir felaket anında topluluğunuzu saatler içinde eski haline getirmenize olanak tanır. Özellikle NFT toplulukları, oyun sunucuları ve kurumsal Discord kanalları için bu tür yedeklemeler, iş sürekliliği açısından bir lüks değil zorunluluktur. Yedekleme yaparken rollerin hiyerarşik sıralamasını ve kanal bazlı özel izinleri kontrol etmeyi ihmal etmeyin."
    },
    {
      title: "Discord API Limitleri (Rate Limiting) ve Hesabınızı Korumak",
      content: "Discord, platformun stabilitesini korumak için her kullanıcı hesabına belirli bir süre içinde yapabileceği işlem sayısı sınırı koyar. Buna 'Rate Limiting' denir. Eğer bir saniye içinde 50 tane kanal oluşturmaya çalışırsanız, Discord hesabınızı geçici olarak askıya alabilir veya işlemi durdurabilir.\n\nOX Cloner, bu limitleri gerçek zamanlı olarak izleyen 'Akıllı Gecikme' (Smart Delay) teknolojisine sahiptir. Her kanal oluşturma veya rol atama işlemi arasında, Discord'un algoritmalarını rahatsız etmeyecek milisaniyelik boşluklar bırakır. 'Hızlı Mod' (Fast Mode) bu gecikmeleri minimize ederken, büyük sunucularda her zaman varsayılan gecikme sürelerini kullanmanızı tavsiye ederiz. Bu sayede hem sunucunuz kusursuz kopyalanır hem de Discord hesabınızın güvenliği tehlikeye atılmaz."
    }
  ],
  en: [
    {
      title: "How to Safely Clone a Discord Server? (Step-by-Step Guide)",
      content: "Copying your Discord server is a very sensitive process, especially when moving large communities to a new structure or backing up critical data. As a first step, you must ensure that you have the necessary permissions on the server you want to copy (source) and the server you will transfer the data to (target). OX Cloner creates a secure bridge between these two servers using your user token.\n\nUsing the 'Safe Mode' option during the process prevents you from being caught by Discord's automated bot detection systems. In this mode, operations proceed more slowly but much more stably. The order of channels, category permissions, and custom emoji sets are analyzed one-to-one by our system and rebuilt on the target server. Remember, having 'Administrator' permission on your account during this process is essential for the complete migration of all hidden channels and private roles."
    },
    {
      title: "The Vital Importance of Server Backup for Digital Communities",
      content: "A Discord server is not just a chat area, it is the product of thousands of hours of effort, private content, and a complex organizational structure. It is possible for this structure to disappear in seconds as a result of cyberattacks, unauthorized bot usage, or administrator errors. This is where regular 'Server Backup' comes in.\n\nStoring an instant 'template' of your server in another empty server with OX Cloner allows you to restore your community to its former state in hours in the event of a disaster. Especially for NFT communities, gaming servers, and corporate Discord channels, such backups are a necessity, not a luxury, for business continuity. Don't forget to check the hierarchical order of roles and channel-based special permissions when backing up."
    },
    {
      title: "Understanding Discord API Limits (Rate Limiting) and Protecting Your Account",
      content: "Discord sets a limit on the number of transactions each user account can perform within a certain period of time to maintain the stability of the platform. This is called 'Rate Limiting'. If you try to create 50 channels in one second, Discord may temporarily suspend your account or stop the transaction.\n\nOX Cloner features 'Smart Delay' technology that monitors these limits in real-time. It leaves millisecond gaps between each channel creation or role assignment process that will not disturb Discord's algorithms. While 'Fast Mode' minimizes these delays, we always recommend using the default delay times on large servers. In this way, both your server is copied perfectly and the security of your Discord account is not compromised."
    }
  ],
  es: [
    {
      title: "¿Cómo clonar de forma segura un servidor de Discord? (Guía paso a paso)",
      content: "Copiar su servidor de Discord es un proceso muy sensible, especialmente cuando se mueven grandes comunidades a una nueva estructura o se realiza una copia de seguridad de datos críticos. Como primer paso, debe asegurarse de tener los permisos necesarios en el servidor que desea copiar (fuente) y en el servidor al que transferirá los datos (destino). OX Cloner crea un puente seguro entre estos dos servidores utilizando su token de usuario.\n\nEl uso de la opción 'Modo seguro' (Safe Mode) durante el proceso evita que sea detectado por los sistemas automatizados de detección de bots de Discord. En este modo, las operaciones avanzan más lentamente pero de forma mucho más estable. El orden de los canales, los permisos de las categorías y los conjuntos de emojis personalizados son analizados uno por uno por nuestro sistema y reconstruidos en el servidor de destino. Recuerde, tener el permiso de 'Administrador' en su cuenta durante este proceso es esencial para la migración completa de todos los canales ocultos y roles privados."
    },
    {
      title: "La importancia vital del respaldo del servidor para las comunidades digitales",
      content: "Un servidor de Discord no es solo un área de chat, es el producto de miles de horas de esfuerzo, contenido privado y una estructura organizativa compleja. Es posible que esta estructura desaparezca en segundos como resultado de ciberataques, uso no autorizado de bots o errores del administrador. Aquí es donde entra en juego el 'Respaldo del servidor' (Backup) regular.\n\nAlmacenar una 'plantilla' (template) instantánea de su servidor en otro servidor vacío con OX Cloner le permite restaurar su comunidad a su estado anterior en horas en caso de un desastre. Especialmente para las comunidades de NFT, servidores de juegos y canales corporativos de Discord, este tipo de respaldos son una necesidad, no un lujo, para la continuidad del negocio. No olvide verificar el orden jerárquico de los roles y los permisos especiales basados en canales al realizar la copia de seguridad."
    },
    {
      title: "Entendiendo los límites de la API de Discord (Rate Limiting) y protegiendo su cuenta",
      content: "Discord establece un límite en la cantidad de transacciones que cada cuenta de usuario puede realizar dentro de un cierto período de tiempo para mantener la estabilidad de la plataforma. Esto se llama 'Rate Limiting'. Si intenta crear 50 canales en un segundo, Discord puede suspender temporalmente su cuenta o detener la transacción.\n\nOX Cloner cuenta con tecnología de 'Retraso inteligente' (Smart Delay) que monitorea estos límites en tiempo real. Deja espacios de milisegundos entre cada proceso de creación de canales o asignación de roles que no perturbarán los algoritmos de Discord. Si bien el 'Modo rápido' (Fast Mode) minimiza estos retrasos, siempre recomendamos usar los tiempos de retraso predeterminados en servidores grandes. De esta manera, su servidor se copia perfectamente y la seguridad de su cuenta de Discord no se ve comprometida."
    }
  ],
  fr: [
    {
      title: "Comment cloner en toute sécurité un serveur Discord ? (Guide étape par étape)",
      content: "Copier votre serveur Discord est un processus très sensible, en particulier lorsque vous déplacez de grandes communautés vers une nouvelle structure ou que vous sauvegardez des données critiques. Dans un premier temps, vous devez vous assurer que vous disposez des autorisations nécessaires sur le serveur que vous souhaitez copier (source) et sur le serveur vers lequel vous transférerez les données (cible). OX Cloner crée un pont sécurisé entre ces deux serveurs à l'aide de votre jeton d'utilisateur.\n\nL'utilisation de l'option 'Mode sécurisé' (Safe Mode) pendant le processus vous évite d'être détecté par les systèmes automatisés de détection de bots de Discord. Dans ce mode, les opérations se déroulent plus lentement mais de manière beaucoup plus stable. L'ordre des salons, les autorisations de catégorie et les ensembles d'emojis personnalisés sont analysés un par un par notre système et reconstruits sur le serveur cible. N'oubliez pas que le fait de disposer de l'autorisation 'Administrateur' sur votre compte pendant ce processus est essentiel pour la migration complète de tous les salons cachés et des rôles privés."
    },
    {
      title: "L'importance vitale de la sauvegarde de serveur pour les communautés numériques",
      content: "Un serveur Discord n'est pas seulement une zone de discussion, c'est le produit de milliers d'heures d'efforts, de contenus privés et d'une structure organisationnelle complexe. Il est possible que cette structure disparaisse en quelques secondes à la suite de cyberattaques, d'une utilisation non autorisée de bots ou d'erreurs d'administrateur. C'est là qu'intervient la 'Sauvegarde de serveur' (Backup) régulière.\n\nStocker un 'modèle' (template) instantané de votre serveur sur un autre serveur vide avec OX Cloner vous permet de restaurer votre communauté dans son état d'origine en quelques heures en cas de catastrophe. En particulier pour les communautés NFT, les serveurs de jeux et les salons Discord d'entreprise, ces types de sauvegardes sont une nécessité, pas un luxe, pour la continuité des activités. N'oubliez pas de vérifier l'ordre hiérarchique des rôles et les autorisations spéciales par salon lors de la sauvegarde."
    },
    {
      title: "Comprendre les limites de l'API Discord (Rate Limiting) et protéger votre compte",
      content: "Discord fixe une limite au nombre de transactions que chaque compte utilisateur peut effectuer pendant une certaine période afin de maintenir la stabilité de la plateforme. C'est ce qu'on appelle le 'Rate Limiting'. Si vous essayez de créer 50 salons en une seconde, Discord peut suspendre temporairement votre compte ou arrêter la transaction.\n\nOX Cloner dispose de la technologie 'Smart Delay' qui surveille ces limites en temps réel. Elle laisse des intervalles de quelques millisecondes entre chaque processus de création de salon ou d'attribution de rôle qui ne perturberont pas les algorithmes de Discord. Bien que le 'Mode rapide' (Fast Mode) minimise ces délais, nous recommandons toujours d'utiliser les délais par défaut sur les serveurs de grande taille. De cette façon, votre serveur est copié parfaitement et la sécurité de votre compte Discord n'est pas compromise."
    }
  ],
  de: [
    {
      title: "Wie klone ich sicher einen Discord-Server? (Schritt-für-Schritt-Anleitung)",
      content: "Das Kopieren Ihres Discord-Servers ist ein sehr sensibler Vorgang, insbesondere wenn Sie große Communities in eine neue Struktur verschieben oder kritische Daten sichern. Als ersten Schritt müssen Sie sicherstellen, dass Sie über die erforderlichen Berechtigungen auf dem Server verfügen, den Sie kopieren möchten (Quelle), und auf dem Server, auf den Sie die Daten übertragen (Ziel). OX Cloner erstellt mithilfe Ihres Benutzer-Tokens eine sichere Brücke zwischen diesen beiden Servern.\n\nDie Verwendung der Option 'Sicherer Modus' (Safe Mode) während des Vorgangs verhindert, dass Sie von den automatisierten Bot-Erkennungssystemen von Discord erfasst werden. In diesem Modus verlaufen die Vorgänge langsamer, aber viel stabiler. Die Reihenfolge der Kanäle, Kategorieberechtigungen und benutzerdefinierten Emoji-Sets werden von unserem System einzeln analysiert und auf dem Zielserver neu aufgebaut. Denken Sie daran, dass die Berechtigung 'Administrator' für Ihr Konto während dieses Vorgangs unerlässlich ist, um alle versteckten Kanäle und privaten Rollen vollständig zu migrieren."
    },
    {
      title: "Die entscheidende Bedeutung von Server-Backups für digitale Communities",
      content: "Ein Discord-Server ist nicht nur ein Chat-Bereich, er ist das Produkt von Tausenden von Stunden Arbeit, privaten Inhalten und einer komplexen Organisationsstruktur. Es ist möglich, dass diese Struktur infolge von Cyberangriffen, nicht autorisierter Bot-Nutzung oder Administratorfehlern in Sekundenschnelle verschwindet. Hier kommt das regelmäßige 'Server-Backup' ins Spiel.\n\nDas Speichern eines sofortigen 'Templates' Ihres Servers auf einem anderen leeren Server mit OX Cloner ermöglicht es Ihnen, Ihre Community im Katastrophenfall innerhalb von Stunden wieder in ihren ursprünglichen Zustand zu versetzen. Insbesondere für NFT-Communities, Gaming-Server und Discord-Kanäle von Unternehmen sind solche Backups eine Notwendigkeit und kein Luxus für die Geschäftskontinuität. Vergessen Sie nicht, bei der Sicherung die hierarchische Reihenfolge der Rollen und kanalbasierten Sonderberechtigungen zu überprüfen."
    },
    {
      title: "Discord-API-Limits (Rate Limiting) verstehen und Ihr Konto schützen",
      content: "Discord legt ein Limit für die Anzahl der Transaktionen fest, die jedes Benutzerkonto innerhalb eines bestimmten Zeitraums durchführen kann, um die Stabilität der Plattform zu gewährleisten. Dies wird als 'Rate Limiting' bezeichnet. Wenn Sie versuchen, 50 Kanäle in einer Sekunde zu erstellen, kann Discord Ihr Konto vorübergehend sperren oder die Transaktion stoppen.\n\nOX Cloner verfügt über die 'Smart Delay'-Technologie, die diese Limits in Echtzeit überwacht. Sie lässt Millisekundenlücken zwischen jedem Kanalerstellungs- oder Rollenzuweisungsprozess, die die Algorithmen von Discord nicht stören. Während der 'Schnelle Modus' (Fast Mode) diese Verzögerungen minimiert, empfehlen wir auf großen Servern immer die Verwendung der Standardverzögerungszeiten. Auf diese Weise wird sowohl Ihr Server perfekt kopiert als auch die Sicherheit Ihres Discord-Kontos nicht gefährdet."
    }
  ],
  pt: [
    {
      title: "Como clonar um servidor do Discord com segurança? (Guia passo a passo)",
      content: "Copiar o seu servidor do Discord é um processo muito sensível, especialmente ao mover grandes comunidades para uma nova estrutura ou ao fazer backup de dados críticos. Como primeiro passo, deve garantir que tem as permissões necessárias no servidor que deseja copiar (origem) e no servidor para o qual transferirá os dados (destino). O OX Cloner cria uma ponte segura entre esses dois servidores usando o seu token de usuário.\n\nO uso da opção 'Modo Seguro' (Safe Mode) durante o processo evita que seja apanhado pelos sistemas automatizados de deteção de bots do Discord. Neste modo, as operações progridem de forma mais lenta, mas muito mais estável. A ordem dos canais, permissões de categoria e conjuntos de emojis personalizados são analisados um a um pelo nosso sistema e reconstruídos no servidor de destino. Lembre-se, ter permissão de 'Administrador' na sua conta durante este processo é essencial para a migração completa de todos os canais ocultos e cargos privados."
    },
    {
      title: "A importância vital do backup de servidor para comunidades digitais",
      content: "Um servidor do Discord não é apenas uma área de chat, é o produto de milhares de horas de esforço, conteúdo privado e uma estrutura organizacional complexa. É possível que esta estrutura desapareça em segundos como resultado de ciberataques, uso não autorizado de bots ou erros do administrador. É aqui que entra o 'Backup de Servidor' regular.\n\nArmazenar um 'modelo' (template) instantâneo do seu servidor noutro servidor vazio com o OX Cloner permite-lhe restaurar a sua comunidade ao seu estado anterior em horas no caso de um desastre. Especialmente para comunidades NFT, servidores de jogos e canais corporativos do Discord, esse tipo de backup é uma necessidade, não um luxo, para a continuidade do negócio. Não se esqueça de verificar a ordem hierárquica dos cargos e as permissões especiais baseadas em canais ao fazer o backup."
    },
    {
      title: "Compreender os limites da API do Discord (Rate Limiting) e proteger a sua conta",
      content: "O Discord define um limite para o número de transações que cada conta de usuário pode realizar dentro de um determinado período de tempo para manter a estabilidade da plataforma. Isso é chamado de 'Rate Limiting'. Se tentar criar 50 canais em um segundo, o Discord pode suspender temporariamente a sua conta ou interromper a transação.\n\nO OX Cloner possui a tecnologia 'Smart Delay' que monitoriza esses limites em tempo real. Deixa intervalos de milissegundos entre cada processo de criação de canal ou atribuição de cargo que não perturbarão os algoritmos do Discord. Embora o 'Modo Rápido' (Fast Mode) minimize esses atrasos, recomendamos sempre o uso dos tempos de atraso padrão em servidores grandes. Desta forma, o seu servidor é copiado perfeitamente e a segurança da sua conta do Discord não é comprometida."
    }
  ],
  it: [
    {
      title: "Come clonare in sicurezza un server Discord? (Guida passo dopo passo)",
      content: "Copiare il tuo server Discord è un processo molto delicato, specialmente quando si spostano grandi comunità in una nuova struttura o si esegue il backup di dati critici. Come primo passo, devi assicurarti di avere i permessi necessari sul server che vuoi copiare (sorgente) e sul server in cui trasferirai i dati (destinazione). OX Cloner crea un ponte sicuro tra questi due server utilizzando il tuo token utente.\n\nL'utilizzo dell'opzione 'Modalità sicura' (Safe Mode) durante il processo impedisce di essere rilevati dai sistemi automatici di rilevamento bot di Discord. In questa modalità, le operazioni procedono più lentamente ma in modo molto più stabile. L'ordine dei canali, i permessi delle categorie e i set di emoji personalizzati vengono analizzati uno per uno dal nostro sistema e ricostruiti sul server di destinazione. Ricorda, avere il permesso 'Amministratore' sul tuo account durante questo processo è essenziale per la migrazione completa di tutti i canali nascosti e dei ruoli privati."
    },
    {
      title: "L'importanza vitale del backup del server per le comunità digitali",
      content: "Un server Discord non è solo un'area di chat, è il prodotto di migliaia di ore di impegno, contenuti privati e una complessa struttura organizzativa. È possibile che questa struttura scompaia in pochi secondi a causa di attacchi informatici, uso non autorizzato di bot o errori dell'amministratore. È qui che entra in gioco il regolare 'Backup del server' (Backup).\n\nMemorizzare un 'modello' (template) istantaneo del tuo server in un altro server vuoto con OX Cloner ti consente di ripristinare la tua comunità allo stato precedente in poche ore in caso di disastro. Specialmente per le comunità NFT, i server di gioco e i canali Discord aziendali, questi tipi di backup sono una necessità, non un lusso, per la continuità operativa. Non dimenticare di controllare l'ordine gerarchico dei ruoli e i permessi speciali basati sui canali durante il backup."
    },
    {
      title: "Capire i limiti delle API di Discord (Rate Limiting) e proteggere il proprio account",
      content: "Discord imposta un limite al numero di transazioni che ogni account utente può eseguire entro un certo periodo di tempo per mantenere la stabilità della piattaforma. Questo si chiama 'Rate Limiting'. Se provi a creare 50 canali in un secondo, Discord potrebbe sospendere temporaneamente il tuo account o interrompere la transazione.\n\nOX Cloner dispone della tecnologia 'Smart Delay' che monitora questi limiti in tempo reale. Lascia intervalli di millisecondi tra ogni processo di creazione di canali o assegnazione di ruoli che non disturberanno gli algoritmi di Discord. Sebbene la 'Modalità rapida' (Fast Mode) riduca al minimo questi ritardi, consigliamo sempre di utilizzare i tempi di ritardo predefiniti sui server di grandi dimensioni. In questo modo, sia il tuo server viene copiato perfettamente, sia la sicurezza del tuo account Discord non viene compromessa."
    }
  ]
};
